### PR TITLE
History example

### PR DESCRIPTION
**Pull request by michielbdejong**
@MattiSG @Ndpnt Please review the commit message and anything else you might notice about this example of what the history branch would end up looking like with the current version of my script.

### CODE REVIEW

**Comment by michielbdejong** [comment]
For instance, the github username is now 'michielbdejong', should I create a github user called something like TosbackCgusBridge?

**Comment by michielbdejong** [comment]
Hm, I also just noticed I should URL-encode links to e.g. "https://github.com/tosdr/tosback2/blob/c1af09562f962141a22960cf63fbad4921800b05/crawl/500px.com/Privacy Policy.txt" in the commit message because there are spaces in it. Will fix that

**Comment by Ndpnt** [comment]
> For instance, the github username is now 'michielbdejong', should I create a github user called something like TosbackCgusBridge?

Hi Michiel,
I do not find it very important be I think it would be better if we could have this kind of generic user. So, if it is not too long for you, it could be nice.
For the name I suggest `TosbackCgusBridge-Bot`.

**Comment by Ndpnt** [comment]
> @MattiSG @Ndpnt Please review the commit message and anything else you might notice about this example of what the history branch would end up looking like with the current version of my script.

I think it could be nice to have commit messages similar to the ones currently made by AmbNum-Bot. So instead of:
```
Allrecipes/Privacy Policy.html (Sat Oct 20 2012)

Imported from https://github.com/tosdr/tosback2/blob/2fecd5eb74052618d004eb38815864a209e54725/crawl/allrecipes.com/Privacy Policy.txt
```
I suggest:
```
Update Allrecipes Privacy Policy (Sat Oct 20 2012)

Imported from https://github.com/tosdr/tosback2/blob/2fecd5eb74052618d004eb38815864a209e54725/crawl/allrecipes.com/Privacy Policy.txt
``` 

Except for the first commit of a service document, replace `Update` by `Start tracking`

**Comment by michielbdejong** [comment]
Changed adopted in https://github.com/ambanum/TOSBack-CGUs-bridge

**Pull request closed without merging**
